FROM maven:3.9.6-amazoncorretto-21 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -Dmaven.test.skip=true

FROM amazoncorretto:21
WORKDIR /app
COPY --from=builder /app/target/OnlineLibrary-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "OnlineLibrary-0.0.1-SNAPSHOT.jar"]